### ISSUE TITLE
trouble running STRetch

### ISSUE THREAD

**Issue by Phillip-a-richmond** [Oshlack/STRetch#33]
Hello,
I would ideally like to use your tool for STR detection, but the whole setup is very confusing. I have never heard of or used bpipe and I think that's one of the difficulties. It is also unclear about which "groovy" pipelines need to be edited.

I am trying to follow along with the instructions for running from a bam file, but I keep getting an error which I don't know how to interpret.

This is my code:

```
SAMPLE_ID='T246-1_BWAmem'
WORKING_DIR='/mnt/causes-vnx2/TIDE/PROCESS/GENOME_TIDEX/T246/HG19/'
GENOME_FASTA='/mnt/causes-vnx1/GENOMES/hg19/FASTA/hg19.fa'
cd $WORKING_DIR
# STRetch
/opt/tools/STRetch/tools/bpipe-0.9.9.2/bin/bpipe run \
        -p input_regions=reference-data/hg19.simpleRepeat_period1-6_dedup.sorted.bed \
        /opt/tools/STRetch/pipelines/STRetch_wgs_bam_pipeline.groovy \
        $WORKING_DIR${SAMPLE_ID}_dupremoved_realigned.sorted.bam
```

I downloaded your reference data for hg19 and the files looks fine for that:

hg19.simpleRepeat_period1-6_dedup.sorted.bed  hg19.STRdecoys.sorted.fasta.ann  hg19.STRdecoys.sorted.fasta.genome  hg19.STR_disease_loci.bed  reference-data.zip
hg19.STRdecoys.sorted.fasta                   hg19.STRdecoys.sorted.fasta.bwt  hg19.STRdecoys.sorted.fasta.pac     PCRfreeWGS.controls.tsv    STRdecoys.fasta
hg19.STRdecoys.sorted.fasta.amb               hg19.STRdecoys.sorted.fasta.fai  hg19.STRdecoys.sorted.fasta.sa      README.txt                 STRdecoys.sorted.bed

The error I get is this:

```====================================================================================================
|                              Starting Pipeline at 2018-09-20 14:14                               |
====================================================================================================

======================================== Stage str_targets =========================================
ERROR: An output containing or ending with '.bed' was referenced.

However such an output was not in the outputs specified by an enclosing transform / filter / produce statement.

Valid outputs according to the enclosing block are: T246-1_BWAmem_dupremoved_realigned.sorted.slop.bam 


========================================= Pipeline Failed ==========================================

An output containing or ending with '.bed' was referenced.

However such an output was not in the outputs specified by an enclosing transform / filter / produce statement.

Valid outputs according to the enclosing block are: T246-1_BWAmem_dupremoved_realigned.sorted.slop.bam

Use 'bpipe errors' to see output from failed commands.

```

Any assistance is helpful. 

Thanks,
Phil

**Comment by hdashnow** [comment]
Hi Phil,

There's no "str_targets" stage in the current version of STRetch. I suspect you're running an older version but using the instructions for the latest version. Could you please update to the latest version and try again?

You shouldn't need to download the reference data separately as it is downloaded by the `install.sh` script. Install instructions are here: (https://github.com/Oshlack/STRetch/wiki/Installing-STRetch)[https://github.com/Oshlack/STRetch/wiki/Installing-STRetch]

To answer your question about bpipe, rather than a single piece of software, STRetch is really a pipeline made up of existing tools (e.g. BWA) and scripts for performing the STR-specific components. Bpipe is a pipeline tool that stitches this all together and can also manage things like submitting jobs to a cluster. For just running STRetch you shouldn't need to edit any `.groovy` files. For example `pipeline_config.groovy` will be created by `install.sh` and you would only need to edit this if wanting to use custom versions of tools etc. If you want a submit many jobs to a cluster for example you would need to do a bit of configuration. If that's the case, let me know and I'll talk you through it.

**Comment by hdashnow** [comment]
I'm going to close this issue for now. Let me know if I can be of any further help.

**Comment by Phillip-a-richmond** [comment]
Actually I got the tool to work this morning! A few extra installs/configurations that I had to work out and it ended up running to completion. 

Thanks again for your help!

-Phil
