### ISSUE TITLE
ERROR with test run (hg19.STRdecoys.sorted.fasta.sa missing from test dataset)

### ISSUE THREAD

**Issue by hchetia** [Oshlack/STRetch#67]
Hi,
I am trying to test run STRetch using the dataset at https://ndownloader.figshare.com/articles/4762489?private_link=cc7347f4637d9a7fe22d and running into the foll. error. (PFA).
Basically, the tool looks for a file "hg19.STRdecoys.sorted.fasta.sa" which is not a part of the test dataset.

[stretch_error.txt](https://github.com/Oshlack/STRetch/files/7435556/stretch_error.txt)

**Comment by hdashnow** [comment]
You can download individual missing files from here in the meantime: https://figshare.com/articles/dataset/STRetch_reference_data_-_hg19/4658701/1

**Comment by hdashnow** [comment]
FigShare wasn't getting back to me about this error, so I've moved the data. Would you mind updated with `git pull` and run the `./install.sh` again. Then let me know if the test data works.

**Comment by hchetia** [comment]
Hi @hdashnow 
I already ran my data using the files you shared above.
Worked fine for me.
Thanks.

**Comment by hdashnow** [comment]
Great!

**Comment by hchetia** [comment]
Hi @hdashnow 
Thanks for STRETCH. Love the concept of decoy chromosomes. 
Do you happen to have a reference hg38 fasta file with the repeats introduced within the genes and their corresponding updated annotations?
Adding 2000 trinucleotide repeats would add 6000 residues to the downstream annotation values right? Any gtf or gff3 format would work.
This genome would be really helpful in visualizing the reads under IGV.

Regards,
Hasna

**Comment by hdashnow** [comment]
I don't have anything like that. I do have some code for generating fasta files with different STR alleles. I used it for simulating reads. But you could potentially use similar logic to create an alternate reference.
https://github.com/quinlan-lab/STRling/blob/master/sim/random_str_alleles.py
I think that visualizing in IGV will still be challenging, because of the anchored reads. When you look at the reads aligned to the STRetch genome + decoy, these anchored reads should show up in a different colour because they align to a different chromosome (the decoy). This can help with visualization.

**Comment by hchetia** [comment]
Awesome. Thanks, will try and get back to you.
